#!/bin/zsh

instance_id=$($DOTFILE_PATH/functions/get_instance_id $1)
pub_ip=$(
  aws ec2 describe-instances \
    --profile ab \
    --region us-east-1 \
    --instance-id "$instance_id" \
    --query 'Reservations[].Instances[].PublicIpAddress' \
    --output text
)

echo $pub_ip
