#!/bin/zsh

external_ip=$($DOTFILE_PATH/functions/external_ip)
identifier='Justin Home'
sg_group_id='sg-08ab2e00f847a811b'
add_new=0

existing_rule=$(
  aws ec2 describe-security-groups \
    --group-ids $sg_group_id \
    --query "SecurityGroups[*].IpPermissions[*].IpRanges[?not_null(Description) && contains(Description, '$identifier')]"
)

if echo $existing_rule | grep -q $identifier; then

  old_ip=$(echo $existing_rule | jq '.[0][0][0].CidrIp')
  if echo $old_ip | grep -q $external_ip; then
    echo 'External IP address has not changed since last update'
  else
    echo 'External IP address has changed'
    echo "Revoking old entry for $old_ip"
    add_new=1
    aws ec2 revoke-security-group-ingress \
      --group-id $sg_group_id \
      --ip-permissions "[{\"IpProtocol\": \"-1\", \"IpRanges\": [{\"CidrIp\": $old_ip}]}]"
  fi

else
  echo "No entries found for this identifier: $identifier"
  add_new=1
fi

if [ "$add_new" -eq "1" ]; then
  echo "Adding new entry for: \"$external_ip/32\""
  aws ec2 authorize-security-group-ingress \
    --group-id $sg_group_id \
    --ip-permissions "[{\"IpProtocol\": \"-1\", \"IpRanges\": [{\"CidrIp\": \"$external_ip/32\", \"Description\": \"$identifier\"}]}]"
else
  echo 'Nothing to update'
fi
