#!/usr/bin/env zsh

if [[ -z "${PROJECTS:-}" ]]; then
  print -u2 'PROJECTS is not set'
  return 1
fi

if [[ -n "${1:-}" && -d "${PROJECTS}/${1}" ]]; then
  cd "${PROJECTS}/${1}" || return
else
  cd "${PROJECTS}" || return
fi
