#!/usr/bin/env zsh

local interface
interface="$(route -n get default 2>/dev/null | awk '/interface:/ { print $2; exit }')"
if [[ -z "${interface}" ]]; then
  print -u2 'Unable to determine the default network interface'
  return 1
fi

ipconfig getifaddr "${interface}"
